version: 0.2
            
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y wget
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install --upgrade awscli
  build:
    commands:
      - make dist
  post_build:
    commands:
      - echo No post build yet
      
artifacts:
  type: zip
  files:
    - './dist/*.zip'
  discard-paths: no
